### ISSUE TITLE
'Tree' object has no attribute 'edges'

### ISSUE THREAD

**Issue by btrainee** [esayyari/DiscoVista#21]
hi , 
    when I run discovista, always some AttributeError ，here is the running log:  
python2 $home/DiscoVista-master/src/utils/discoVista.py -c ./parameters/clade-defs.txt -p ./genetrees/filtered/ -t 75 -y ./parameters/newModel.txt -w ./parameters/newOrders.txt -m 1 -o ./genetrees/filtered/results
Number of trees found is: 2532
Traceback (most recent call last):
  File "$home/DiscoVista-master/src/utils/discoVista.py", line 60, in <module>
    analyzer.analyze()
  File "$home/DiscoVista-master/src/utils/analyze.py", line 302, in analyze
    self.treesAnalyses()
  File "$home/DiscoVista-master/src/utils/analyze.py", line 119, in treesAnalyses
    tools.remove_edges_from_tree(tree, opt.threshold)
  File "$home/DiscoVista-master/src/utils/tools.py", line 45, in remove_edges_from_tree
    edges = set(tree.edges(filt))
AttributeError: 'Tree' object has no attribute 'edges'

so I wonder there is something wrong with this command ?

**Comment by btrainee** [comment]
Resolved!
