### ISSUE TITLE
KeyError: 'WS_HOME'

### ISSUE THREAD

**Issue by liuxi1998** [esayyari/DiscoVista#22]
Why does the "KeyError: 'WS_HOME'" occur? But it was normal several months ago? Did anyone encounter the same problem as me?

python2 /data/01/user156/fenshu/ONT/01.genomic_comparison/5.phylogenetic/split_window/DiscoVista/src/utils/discoVista.py -p ./tree  -m 5 -a annotation.txt -o ./tree/results -g paradxus

Traceback (most recent call last):
  File "/data/01/user156/fenshu/ONT/01.genomic_comparison/5.phylogenetic/split_window/DiscoVista/src/utils/discoVista.py", line 60, in <module>
    analyzer.analyze()
  File "/data/01/user156/fenshu/ONT/01.genomic_comparison/5.phylogenetic/split_window/DiscoVista/src/utils/analyze.py", line 310, in analyze
    self.relFreq()
  File "/data/01/user156/fenshu/ONT/01.genomic_comparison/5.phylogenetic/split_window/DiscoVista/src/utils/analyze.py", line 280, in relFreq
    WS_HOME = os.environ['WS_HOME']
  File "/usr/lib64/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
**KeyError: 'WS_HOME'**

**Comment by btrainee** [comment]
Encountered the same problem with you.

**Comment by btrainee** [comment]
Then you need to set environmental variable WS_HOME to the directory under which DiscoVista repository is placed. For example, if you clone to DiscoVista and placed it under the /Users/Erfan/reposiotry folder, then you would export WS_HOME as /Users/Erfan/reposiotry.

**Comment by liuxi1998** [comment]
Thank you very much. It works well. However, the other error occurred. I checked my annotation file, and there was no wrong.  
USAGE: [PATH] [annotation] [names] [OUTDIR] [outgroup]
outgroup is Base
  File "/data/01/user156/fenshu/ONT/01.genomic_comparison/5.phylogenetic/split_window/DiscoVista/src/utils//check-anot-if-mono.py", line 20
    alltmp = tree_tmp.encode_bipartitions(is_bipartitions_mutable = False)
**TabError: inconsistent use of tabs and spaces in indentation**
