### ISSUE TITLE
TypeError: float() argument must be a string or a number

### ISSUE THREAD

**Issue by Galaxy-228** [esayyari/DiscoVista#23]
Hi~
I met the following error:
number of contracted trees is :953
Number of trees to analyze is: 953
WARNING some support was not available. Ignoring this branch  length was:  0.0394150663 clade was:  [<Taxon 0x7efd625e5a90 'Aal'>, <Taxon 0x7efd625e5c90 'Dni'>, <Taxon 0x7efd625e5bd0 'Ali'>] tree is:  (Cpa:0.474046,Tha:0.0847808929,(Aar:0.117421439......
Traceback (most recent call last):
  File "/repository/DiscoVista/src/utils/discoVista.py", line 59, in <module>
    analyzer.analyze()
  File "/repository/DiscoVista/src/utils/analyze.py", line 302, in analyze
    self.treesAnalyses()
  File "/repository/DiscoVista/src/utils/analyze.py", line 140, in treesAnalyses
    find_clades2.main(opt.names, opt.clades, outFile, multiplier, searchFiles)
  File "/repository/DiscoVista/src/utils/find_clades2.py", line 321, in main
    mono.analyze(tree, treeName, mult)
  File "/repository/DiscoVista/src/utils/find_clades2.py", line 172, in analyze
    self.analyze_clade(k, v, clade_comp, tree, treeName, mult, allBiparts)
  File "/repository/DiscoVista/src/utils/find_clades2.py", line 155, in analyze_clade
    self.check_mono(tree, treeName, taxa, name, len(taxa) == len(clade), ofile, mult, allBiparts)
  File "/repository/DiscoVista/src/utils/find_clades2.py", line 105, in check_mono
    self.print_result(treeName, "IS_MONO", bipartition, name, tree, ofile, mult, clade)
  File "/repository/DiscoVista/src/utils/find_clades2.py", line 63, in print_result
    if RepresentsInt(support) and RepresentsInt(mult):
  File "/repository/DiscoVista/src/utils/find_clades2.py", line 9, in RepresentsInt
    float(s)
TypeError: float() argument must be a string or a number

I do not know how to deal with it..
Thanks so much !!!!!

**Comment by bfauskee** [comment]
I have the same issue, error below:
Number of trees found is: 4148
number of contracted trees is :4148
Number of trees to analyze is: 4148
WARNING some support was not available. Ignoring this branch  length was:  2.0719e-06 clade was:  [<Taxon 0x4003db8110 'Microcebus_tavaratra'>, <Taxon 0x4003db8050 'Microcebus_mittermeiri'>, <Taxon 0x4003db80d0 'Microcebus_jonahi'>] tree is:  (Mirza_zaza:0.0021970387,Microcebus_murinus:0.17072803,(Microcebus_griseorufus:2.0719e-06,(Microcebus_ravelobensis:2.0719e-06,((Microcebus_tavaratra:0.0,Microcebus_jonahi:0.0):0.0,Microcebus_mittermeiri:0.0):2.0719e-06)26:2.0719e-06)37:2.0719e-06)
    analyzer.analyze()
  File "/repository/DiscoVista/src/utils/analyze.py", line 302, in analyze
    self.treesAnalyses()
  File "/repository/DiscoVista/src/utils/analyze.py", line 140, in treesAnalyses
    find_clades2.main(opt.names, opt.clades, outFile, multiplier, searchFiles) 
  File "/repository/DiscoVista/src/utils/find_clades2.py", line 321, in main
    mono.analyze(tree, treeName, mult)
  File "/repository/DiscoVista/src/utils/find_clades2.py", line 172, in analyze
    self.analyze_clade(k, v, clade_comp, tree, treeName, mult, allBiparts)
  File "/repository/DiscoVista/src/utils/find_clades2.py", line 155, in analyze_clade
    self.check_mono(tree, treeName, taxa, name, len(taxa) == len(clade), ofile, mult, allBiparts)
  File "/repository/DiscoVista/src/utils/find_clades2.py", line 105, in check_mono
    self.print_result(treeName, "IS_MONO", bipartition, name, tree, ofile, mult, clade)
  File "/repository/DiscoVista/src/utils/find_clades2.py", line 63, in print_result
    if RepresentsInt(support) and RepresentsInt(mult):
  File "/repository/DiscoVista/src/utils/find_clades2.py", line 9, in RepresentsInt
    float(s)
TypeError: float() argument must be a string or a number

Hopefully someone can provide some assistance!

**Comment by IanDMedeiros** [comment]
Getting the identical error. Running the latest version of DiscoVista on a RHEL hpc cluster and an a MacBook Pro---same issue with both.

**Comment by IanDMedeiros** [comment]
This seems to be an issue with IQ-TREE outputting zero-length branches where the length is printed as "" rather than "0".
