### ISSUE TITLE
Relative frequency can't run example and error

### ISSUE THREAD

**Issue by Kekeyang221** [esayyari/DiscoVista#31]
Hi there:

 I'm  trying to run the frequency and using example file. But something is wrong. I don't know how to solve it. I download this zip file, and add "export WS_HOME=/home/yangk/software" in .bashrc. I have also installed the R packages, like "reshape","reshape2","ggplot2","plyr","scales","ape","optparse" and DendroPy. 

  My command is "$WS_HOME/DiscoVista/src/utils/discoVista.py -a parameters/annotation-1.txt -m 5 -p relativeFreq/astral.trim50genes33taxa.no3rd.final-FNA2AA/ -o results -g Base".

   My linux command line shows error message below:
printing errors on results/error.log
['bash', '/home/yangk/software/DiscoVista/src/utils/pos-for-hyp.sh', '/home/yangk/software/DiscoVista/example/1KP/relativeFreq/astral.trim50genes33taxa.no3rd.final-FNA2AA', '/home/yangk/software/DiscoVista/example/1KP/parameters/annotation-1.txt', '/home/yangk/software/DiscoVista/example/1KP/parameters/names.txt', 'results', 'Base']
['bash', '/home/yangk/software/DiscoVista/src/utils/pos-for-hyp.sh', '/home/yangk/software/DiscoVista/example/1KP/relativeFreq/astral.trim50genes33taxa.no3rd.final-FNA2AA', '/home/yangk/software/DiscoVista/example/1KP/parameters/annotation-1.txt', '/home/yangk/software/DiscoVista/example/1KP/parameters/names.txt', 'results', 'Base']

  The generated files in my results shows below:
annotation-1.txt
annotation-1.txt.with.header.txt
astral-job.log
error.log
estimated_gene_trees.tree
estimated_species_tree.tree
estimated_species_tree.tree-hypo.tre
main-hypo.tre
names.txt

  My error.log file shows below:
USAGE: [PATH] [annotation] [names] [OUTDIR] [outgroup]
outgroup is Base
True ['Entransia_fimbriata', 'Klebsormidium_subtile', 'Spirotaenia_minuta', 'Chlorokybus_atmophyticus', 'Mesostigma_viride', 'Uronema_sp', 'Mono>
True ['Penium_margaritaceum', 'Cosmarium_ochthodes', 'Roya_obtusa', 'Netrium_digitus', 'Spirogyra_sp', 'Cylindrocystis_cushleckae', 'Mougeotia_s>
True ['Coleochaete_irregularis', 'Coleochaete_scutata', 'Chaetosphaeridium_globosum'] Coleochaetales
True ['Catharanthus_roseus', 'Allamanda_cathartica', 'Ipomoea_purpurea', 'Rosmarinus_officinalis', 'Tanacetum_parthenium', 'Inula_helenium', 'Di>
True ['Chara_vulgaris'] Charales
All clades specified in the annotation file are monophyletic
True
Hypo
set(['Base', 'Coleochaetales', 'Zygnematophyceae', 'Charales'])
['Base#Charales:2', 'Coleochaetales#Base#Charales:1', 'Zygnematophyceae#Coleochaetales#Base#Charales:1']
Counter({'Base': 1, 'Coleochaetales': 1, 'Zygnematophyceae': 1, 'Landplants': 1, 'Charales': 1})
3
()

  My astral-job.log file shows below:
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: phylonet/tree/io/ParseException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ClassNotFoundException: phylonet.tree.io.ParseException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 7 more
 
  Thank you in advance for any help and I am looking forward to your early reply!

**Comment by JhinAir** [comment]
hi, have you resolved this? I came across the same error.
