### ISSUE TITLE
ImportError: No module named dendropy

### ISSUE THREAD

**Issue by jaaguirresant** [esayyari/DiscoVista#8]
Hi, I'm struggling to run discoVista, which I installed from the source code (I tried with docker but failed to understand the tutorial for this as I never used docker before). When I execute the command ./discoVista.py (located in DiscoVista/src/utils/) I get the following error: "ImportError: No module named dendropy." I did install dendropy. However, it installed it with pyhton3 instead of python2.7. Maybe that's the issue? if so, should I try to install dendropy again with python2.7 and try again?

Thanks

**Comment by esayyari** [comment]
Hi,

Can you please send me the exact commands that you used for installation as well as how you run DiscoVista.

Best,
Erfan

**Comment by jaaguirresant** [comment]
Hi Erfan, thank you for your quick reply! Here's what I did:

1. Created the environmental variable WS_HOME:

`export WS_HOME=/users/juliansoda/repository/`

2. Installed Dendropy:

`python3 -m pip install --upgrade git+https://github.com/jeetsukumaran/DendroPy.git`

`# Output message: "Successfully installed DendroPy-4.4.0"`

3. Executed DiscoVista following the instructions in your GitHub page:

Try 1: 

`cd $WS_HOME/DiscoVista/`
`./discoVista.py`
`# Output message: "-bash: ./discoVista.py: No such file or directory"`

Try 2:

`cd $WS_HOME/DiscoVista/src/utils/`
`./discoVista.py`
`# Output message: "Traceback (most recent call last):
  File "./discoVista.py", line 8, in <module>
    import find_clades 
  File "/Users/juliansoda/repository/DiscoVista/src/utils/find_clades.py", line 7, in <module>
    import dendropy
ImportError: No module named dendropy"`

I hope this is useful. Thank you for your help.

Julián

**Comment by jaaguirresant** [comment]
Erfan, I forgot to say that I also tried the following:

`python3 ./discoVista.py`
`# Output message: "Traceback (most recent call last):
  File "./discoVista.py", line 8, in <module>
    import find_clades 
  File "/Users/juliansoda/repository/DiscoVista/src/utils/find_clades.py", line 124
    print "In %s, %s is not defined before" %(r[0],e.args[0])
                                          ^
SyntaxError: invalid syntax"`

**Comment by esayyari** [comment]
Hi Julian,

Thanks for your follow-up! DiscoVista needs python2.7 (python2 in general). If you prefer condo please try this:

Conda create -n py2.7 python=2.7
Conda activate py2.7
Pip install dendropy

And try ./discovista.py and let me know if you still have the same issue or not.

Thanks for using DiscoVista,
Erfan
